### ISSUE TITLE
Open-sourcing the application

### ISSUE THREAD

**Issue by NickTikhonov** [education/classroom-desktop#10]
The application should be made open-source, and the release versions should be migrated to this repository (currently they are [here](https://github.com/NickTikhonov/electron-desktop-test-releases/releases)). Before this can be done, I will double check to make sure this repo never stored sensitive information. CC @johndbritton

**Comment by tarebyte** [comment]
Done! I went through the commits as well 😄

**Comment by NickTikhonov** [comment]
Thanks for double checking @tarebyte! 💯

**Comment by johndbritton** [comment]
:heart:
