### ISSUE TITLE
Packaging/Autoupdating for Linux

### ISSUE THREAD

**Issue by NickTikhonov** [education/classroom-desktop#13]
It should be possible to package, release and auto-update the application for Windows as well as MacOS. This would be desirable as it will give more teachers access to the features this app will provide.

CC @johndbritton @tarebyte

**Comment by PeterDaveHello** [comment]
Does that means if I simply replace `darwin` with `win32` or `linux` in the packaging command:  `electron-packager . 'GitHub Classroom' --icon=app/resources/icon.icns --platform=darwin --arch=x64 --out=dist --overwrite`, it will not work?

Thanks!

**Comment by johndbritton** [comment]
It should be pretty easy to get this working cross platform, but it's not been tested.

**Comment by PeterDaveHello** [comment]
I tested it but not sure if I missed anything since I got empty(white) window on both Windows and Linux, and exception with white window on macOS, I'll try to test on different platforms and give a more detail report.
