### ISSUE TITLE
cloning repository requires token (and OAuth app?)

### ISSUE THREAD

**Issue by shiftkey** [education/classroom-desktop#32]
Using the example account baked into the application, it tries to clone a number of repositories which represent the (private) student repositories.

Nodegit expects some credentials to be provided, but I can't spot anywhere in the app where this is managed. Ideally, the application should OAuth on behalf of the user and request a token - it'll need `repo` scope to access private repositories - and this should be stored with the app.

I haven't stumbled upon code to manage any of this this in the existing codebase, so please point me to anything existing around this if we can save some time.

**Comment by johndbritton** [comment]
> Nodegit expects some credentials to be provided, but I can't spot anywhere in the app where this is managed.

This is currently unimplemented. We need to build a sign in flow / oauth with corresponding GitHub application. This may behave similar to how GitHub Desktop behaves.

**Comment by srinjoym** [comment]
Fixed with #46
